### ISSUE TITLE
TypeError: The values of index must be integers

### ISSUE THREAD

**Issue by SWHL** [RapidAI/TableStructureRec#4]
### Discussed in https://github.com/RapidAI/TableStructureRec/discussions/2

<div type='discussions-op-text'>

<sup>Originally posted by **hopegithub** December  4, 2023</sup>
我运行了作者提供的examle中无表格线示例，但报错，我查看我的输入没有问题，是一张表格图片
代码：
```python
# -*- encoding: utf-8 -*-
# @Author: SWHL
# @Contact: liekkaskono@163.com
from pathlib import Path

from lineless_table_rec import LinelessTableRecognition

engine = LinelessTableRecognition()

img_path = "../test11.jpg"
table_str, elapse = engine(img_path)

print(table_str)
print(elapse)

with open(f"{Path(img_path).stem}.html", "w", encoding="utf-8") as f:
    f.write(table_str)

print("ok")
```

报错：
```bash
WARNING:root:Traceback (most recent call last):
  File "D:\anaconda\envs\paddleocr\lib\site-packages\lineless_table_rec\main.py", line 54, in __call__
    polygons, slct_logi = self.infer(input_info)
  File "D:\anaconda\envs\paddleocr\lib\site-packages\lineless_table_rec\main.py", line 105, in infer
    slct_logi_feat, slct_dets_feat, slct_output_dets = self.det_process(
  File "D:\anaconda\envs\paddleocr\lib\site-packages\lineless_table_rec\lineless_table_process.py", line 26, in __call__
    dets, keep, logi, cr = ctdet_4ps_decode(
  File "D:\anaconda\envs\paddleocr\lib\site-packages\lineless_table_rec\lineless_table_process.py", line 107, in ctdet_4ps_decode
    scores, inds, clses, ys, xs = _topk(heat, K=K)
  File "D:\anaconda\envs\paddleocr\lib\site-packages\lineless_table_rec\lineless_table_process.py", line 206, in _topk
    topk_inds = _gather_feat(topk_inds.reshape(batch, -1, 1), topk_ind).reshape(
  File "D:\anaconda\envs\paddleocr\lib\site-packages\lineless_table_rec\lineless_table_process.py", line 251, in _gather_feat
    feat = _gather(feat, 1, ind)
  File "D:\anaconda\envs\paddleocr\lib\site-packages\lineless_table_rec\lineless_table_process.py", line 277, in _gather
    raise TypeError("The values of index must be integers")
TypeError: The values of index must be integers

Traceback (most recent call last):
  File "D:\工作\checkreport_table\testcode\lineless.py", line 13, in <module>
    print(table_str)
KeyboardInterrupt

Process finished with exit code -1073741510 (0xC000013A: interrupted by Ctrl+C)
```

请问是什么原因导致的呢</div>
运行操作系统：Windows上有问题，Linux和Mac OS没有问题
报错版本：`wired_table_rec==0.0.1`和`lineless_table_rec==0.0.1`

**Comment by ilovesouthpark** [comment]
巧了，同一天发现同样的问题，谢谢更新，已解决。pip的文件还没有更新（12月14日0点），需要单独下载repo里的替换。windows。

**Comment by SWHL** [comment]
已经在`wired_table_rec==0.0.2`和`lineless_table_rec==0.0.2`解决
