### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by liiuzq-xiaobai** [RapidAI/TableStructureRec#7]
Traceback (most recent call last):
  File "/home/lzq/graduate/projects/TableStructureRec/demo_lineless.py", line 8, in <module>
    engine = LinelessTableRecognition()
  File "/home/lzq/graduate/projects/TableStructureRec/lineless_table_rec/main.py", line 39, in __init__
    self.det_session = OrtInferSession(detect_model_path)
  File "/home/lzq/graduate/projects/TableStructureRec/lineless_table_rec/utils.py", line 18, in __init__
    self.verify_exist(model_path)
  File "/home/lzq/graduate/projects/TableStructureRec/lineless_table_rec/utils.py", line 72, in verify_exist
    raise FileNotFoundError(f"{model_path} does not exist!")
FileNotFoundError: /home/lzq/graduate/projects/TableStructureRec/lineless_table_rec/models/lore_detect.onnx does not exist!
运行无线框demo出现的问题

**Comment by SWHL** [comment]
错误原因：onnx模型不存在。因为仓库中并不包含onnx模型。
建议：`pip install lineless_table_rec`使用。whl包中是包含模型的。

**Comment by KrisTopherHao** [comment]
> 错误原因：onnx模型不存在。因为仓库中并不包含onnx模型。 建议：`pip install lineless_table_rec`使用。whl包中是包含模型的。

你好，我用了pip install lineless_table_rec，而且在PYPI上下载了whl包，pip安装了，还是没有那个onnx文件，还是报错。

**Comment by SWHL** [comment]
直接下载whl包，解压，里面就能看到onnx包的
